// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CoupleExpenses.Infrastructure.Tests.Scenarios
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Period")]
    public partial class PeriodFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Period.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Period", "In order to avoid silly mistakes\r\nAs a math idiot\r\nI want to be told the sum of t" +
                    "wo numbers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line 7
 testRunner.Given("Je suis connecté à l\'application avec l\'utilisateur aurelien et le mot de passe 0" +
                    "f46f2fb6f5a91c79e86acc5da7df95176b4e4c7", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Création d\'une nouvelle période")]
        public virtual void CreationDUneNouvellePeriode()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Création d\'une nouvelle période", ((string[])(null)));
#line 9
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 10
 testRunner.When("Je demande la création d\'une période pour le mois 1 et l\'année 2001", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
 testRunner.Then("La liste des périodes contient \"Janvier 2001\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Intérdire la création de deux mêmes périodes")]
        public virtual void InterdireLaCreationDeDeuxMemesPeriodes()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Intérdire la création de deux mêmes périodes", ((string[])(null)));
#line 13
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 14
 testRunner.And("J\'ai demandé la création d\'une période pour le mois 1 et l\'année 2001", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
 testRunner.When("Je demande la création d\'une période pour le mois 1 et l\'année 2001", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 16
 testRunner.Then("Le serveur me retourne une erreur 400 avec le message \"La période Janvier 2001 ex" +
                    "iste déjà.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Ajouter une dépense à une période")]
        public virtual void AjouterUneDepenseAUnePeriode()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Ajouter une dépense à une période", ((string[])(null)));
#line 18
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 19
 testRunner.And("J\'ai demandé la création d\'une période pour le mois 1 et l\'année 2001", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Periode",
                        "Montant",
                        "Libelle",
                        "Binome",
                        "TypeOperation"});
            table1.AddRow(new string[] {
                        "2001-01",
                        "100",
                        "Test",
                        "Aurélien",
                        "Commun"});
#line 20
 testRunner.When("J\'ajoute des dépenses dans l\'application", ((string)(null)), table1, "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "operationId",
                        "Periode",
                        "Montant",
                        "Libelle",
                        "Binome",
                        "TypeOperation"});
            table2.AddRow(new string[] {
                        "Dépense",
                        "1",
                        "2001-01",
                        "100",
                        "Test",
                        "Aurélien",
                        "Commun"});
#line 23
 testRunner.Then("La liste des opérations pour la période 2001-01 contient les elements suivants", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Ajouter une recette à une période")]
        public virtual void AjouterUneRecetteAUnePeriode()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Ajouter une recette à une période", ((string[])(null)));
#line 27
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 28
 testRunner.And("J\'ai demandé la création d\'une période pour le mois 1 et l\'année 2001", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Periode",
                        "Montant",
                        "Libelle",
                        "Binome",
                        "TypeOperation"});
            table3.AddRow(new string[] {
                        "2001-01",
                        "200",
                        "Test de recette",
                        "Marie",
                        "Commun"});
#line 29
 testRunner.When("J\'ajoute des recettes dans l\'application", ((string)(null)), table3, "When ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "OperationId",
                        "Periode",
                        "Montant",
                        "Libelle",
                        "Binome",
                        "TypeOperation"});
            table4.AddRow(new string[] {
                        "Recette",
                        "1",
                        "2001-01",
                        "200",
                        "Test de recette",
                        "Marie",
                        "Commun"});
#line 32
 testRunner.Then("La liste des opérations pour la période 2001-01 contient les elements suivants", ((string)(null)), table4, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Supprimer une dépense d\'une période")]
        public virtual void SupprimerUneDepenseDUnePeriode()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Supprimer une dépense d\'une période", ((string[])(null)));
#line 36
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 37
testRunner.And("J\'ai demandé la création d\'une période pour le mois 1 et l\'année 2001", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Periode",
                        "Montant",
                        "Libelle",
                        "Binome",
                        "TypeOperation"});
            table5.AddRow(new string[] {
                        "2001-01",
                        "100",
                        "Test",
                        "Aurélien",
                        "Commun"});
#line 38
 testRunner.And("J\'ai ajouté des dépenses dans l\'application", ((string)(null)), table5, "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "OperationId",
                        "Periode",
                        "Montant",
                        "Libelle",
                        "Binome",
                        "TypeOperation"});
            table6.AddRow(new string[] {
                        "Dépense",
                        "1",
                        "2001-01",
                        "100",
                        "Test",
                        "Aurélien",
                        "Commun"});
#line 41
 testRunner.And("La liste des opérations pour la période 2001-01 contient les elements suivants", ((string)(null)), table6, "And ");
#line 44
 testRunner.When("Je demande à supprimer l\'opération 1 de la période 2001-01", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 45
 testRunner.Then("La liste des opérations pour la période 2001-01 est vide", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Supprimer une recette d\'une période")]
        public virtual void SupprimerUneRecetteDUnePeriode()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Supprimer une recette d\'une période", ((string[])(null)));
#line 47
 this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 48
testRunner.And("J\'ai demandé la création d\'une période pour le mois 1 et l\'année 2001", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Periode",
                        "Montant",
                        "Libelle",
                        "Binome",
                        "TypeOperation"});
            table7.AddRow(new string[] {
                        "2001-01",
                        "100",
                        "Test",
                        "Aurélien",
                        "Commun"});
#line 49
 testRunner.And("J\'ai ajouté des recettes dans l\'application", ((string)(null)), table7, "And ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "OperationId",
                        "Periode",
                        "Montant",
                        "Libelle",
                        "Binome",
                        "TypeOperation"});
            table8.AddRow(new string[] {
                        "Recette",
                        "1",
                        "2001-01",
                        "100",
                        "Test",
                        "Aurélien",
                        "Commun"});
#line 52
 testRunner.And("La liste des opérations pour la période 2001-01 contient les elements suivants", ((string)(null)), table8, "And ");
#line 55
 testRunner.When("Je demande à supprimer l\'opération 1 de la période 2001-01", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 56
 testRunner.Then("La liste des opérations pour la période 2001-01 est vide", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Modifier le montant d\'une opération de recette")]
        public virtual void ModifierLeMontantDUneOperationDeRecette()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Modifier le montant d\'une opération de recette", ((string[])(null)));
#line 58
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 59
testRunner.And("J\'ai demandé la création d\'une période pour le mois 1 et l\'année 2001", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Periode",
                        "Montant",
                        "Libelle",
                        "Binome",
                        "TypeOperation"});
            table9.AddRow(new string[] {
                        "2001-01",
                        "100",
                        "Test",
                        "Marie",
                        "Commun"});
#line 60
 testRunner.And("J\'ai ajouté des recettes dans l\'application", ((string)(null)), table9, "And ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "OperationId",
                        "Periode",
                        "Montant",
                        "Libelle",
                        "Binome",
                        "TypeOperation"});
            table10.AddRow(new string[] {
                        "Recette",
                        "1",
                        "2001-01",
                        "100",
                        "Test",
                        "Marie",
                        "Commun"});
#line 63
 testRunner.And("La liste des opérations pour la période 2001-01 contient les elements suivants", ((string)(null)), table10, "And ");
#line 66
 testRunner.When("je demande à modifier le montant de la recette numéro 1 en 200 euros pour la péri" +
                    "ode 2001-01", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 67
 testRunner.Then("L\'opération 1 de la période 2001-01 à un montant de 200 euros", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 68
 testRunner.And("Marie doit la somme de 100 euros pour la période 2001-01", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Modifier le libellé d\'une opération de recette")]
        public virtual void ModifierLeLibelleDUneOperationDeRecette()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Modifier le libellé d\'une opération de recette", ((string[])(null)));
#line 70
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 71
testRunner.And("J\'ai demandé la création d\'une période pour le mois 1 et l\'année 2001", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Periode",
                        "Montant",
                        "Libelle",
                        "Binome",
                        "TypeOperation"});
            table11.AddRow(new string[] {
                        "2001-01",
                        "100",
                        "Test",
                        "Marie",
                        "Commun"});
#line 72
 testRunner.And("J\'ai ajouté des recettes dans l\'application", ((string)(null)), table11, "And ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "OperationId",
                        "Periode",
                        "Montant",
                        "Libelle",
                        "Binome",
                        "TypeOperation"});
            table12.AddRow(new string[] {
                        "Recette",
                        "1",
                        "2001-01",
                        "100",
                        "Test",
                        "Marie",
                        "Commun"});
#line 75
 testRunner.And("La liste des opérations pour la période 2001-01 contient les elements suivants", ((string)(null)), table12, "And ");
#line 78
 testRunner.When("je demande à modifier le libellé de la recette numéro 1 en \"essai\" pour la périod" +
                    "e 2001-01", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 79
 testRunner.Then("L\'opération 1 de la période 2001-01 à pour libellé \"essai\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 80
 testRunner.And("Marie doit la somme de 50 euros pour la période 2001-01", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Modifier le binôme d\'une opération de recette")]
        public virtual void ModifierLeBinomeDUneOperationDeRecette()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Modifier le binôme d\'une opération de recette", ((string[])(null)));
#line 82
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 83
testRunner.And("J\'ai demandé la création d\'une période pour le mois 1 et l\'année 2001", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Periode",
                        "Montant",
                        "Libelle",
                        "Binome",
                        "TypeOperation"});
            table13.AddRow(new string[] {
                        "2001-01",
                        "100",
                        "Test",
                        "Marie",
                        "Commun"});
#line 84
 testRunner.And("J\'ai ajouté des recettes dans l\'application", ((string)(null)), table13, "And ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "OperationId",
                        "Periode",
                        "Montant",
                        "Libelle",
                        "Binome",
                        "TypeOperation"});
            table14.AddRow(new string[] {
                        "Recette",
                        "1",
                        "2001-01",
                        "100",
                        "Test",
                        "Marie",
                        "Commun"});
#line 87
 testRunner.And("La liste des opérations pour la période 2001-01 contient les elements suivants", ((string)(null)), table14, "And ");
#line 90
 testRunner.When("je demande à modifier le binôme de la recette numéro 1 par Aurélien pour la pério" +
                    "de 2001-01", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 91
 testRunner.Then("L\'opération 1 de la période 2001-01 à pour binôme Aurélien", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 92
 testRunner.And("Aurélien doit la somme de 50 euros pour la période 2001-01", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Modifier le type d\'une opération de recette")]
        public virtual void ModifierLeTypeDUneOperationDeRecette()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Modifier le type d\'une opération de recette", ((string[])(null)));
#line 94
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 95
testRunner.And("J\'ai demandé la création d\'une période pour le mois 1 et l\'année 2001", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "Periode",
                        "Montant",
                        "Libelle",
                        "Binome",
                        "TypeOperation"});
            table15.AddRow(new string[] {
                        "2001-01",
                        "100",
                        "Test",
                        "Marie",
                        "Commun"});
#line 96
 testRunner.And("J\'ai ajouté des recettes dans l\'application", ((string)(null)), table15, "And ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "OperationId",
                        "Periode",
                        "Montant",
                        "Libelle",
                        "Binome",
                        "TypeOperation"});
            table16.AddRow(new string[] {
                        "Recette",
                        "1",
                        "2001-01",
                        "100",
                        "Test",
                        "Marie",
                        "Commun"});
#line 99
 testRunner.And("La liste des opérations pour la période 2001-01 contient les elements suivants", ((string)(null)), table16, "And ");
#line 102
 testRunner.When("je demande à modifier le type de la recette numéro 1 en \"Individuelle\" pour la pé" +
                    "riode 2001-01", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 103
 testRunner.Then("L\'opération 1 de la période 2001-01 à pour type \"Individuelle\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 104
 testRunner.And("Marie doit la somme de 100 euros pour la période 2001-01", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Modifier le montant d\'une opération de dépense")]
        public virtual void ModifierLeMontantDUneOperationDeDepense()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Modifier le montant d\'une opération de dépense", ((string[])(null)));
#line 106
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 107
testRunner.And("J\'ai demandé la création d\'une période pour le mois 1 et l\'année 2001", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "Periode",
                        "Montant",
                        "Libelle",
                        "Binome",
                        "TypeOperation"});
            table17.AddRow(new string[] {
                        "2001-01",
                        "100",
                        "Test",
                        "Marie",
                        "Commun"});
#line 108
 testRunner.And("J\'ai ajouté des dépenses dans l\'application", ((string)(null)), table17, "And ");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "OperationId",
                        "Periode",
                        "Montant",
                        "Libelle",
                        "Binome",
                        "TypeOperation"});
            table18.AddRow(new string[] {
                        "Dépense",
                        "1",
                        "2001-01",
                        "100",
                        "Test",
                        "Marie",
                        "Commun"});
#line 111
 testRunner.And("La liste des opérations pour la période 2001-01 contient les elements suivants", ((string)(null)), table18, "And ");
#line 114
 testRunner.When("je demande à modifier le montant de la dépense numéro 1 en 200 euros pour la péri" +
                    "ode 2001-01", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 115
 testRunner.Then("L\'opération 1 de la période 2001-01 à un montant de 200 euros", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 116
 testRunner.And("Aurélien doit la somme de 100 euros pour la période 2001-01", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Modifier le libellé d\'une opération de dépense")]
        public virtual void ModifierLeLibelleDUneOperationDeDepense()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Modifier le libellé d\'une opération de dépense", ((string[])(null)));
#line 118
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 119
testRunner.And("J\'ai demandé la création d\'une période pour le mois 1 et l\'année 2001", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "Periode",
                        "Montant",
                        "Libelle",
                        "Binome",
                        "TypeOperation"});
            table19.AddRow(new string[] {
                        "2001-01",
                        "100",
                        "Test",
                        "Marie",
                        "Commun"});
#line 120
 testRunner.And("J\'ai ajouté des dépenses dans l\'application", ((string)(null)), table19, "And ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "OperationId",
                        "Periode",
                        "Montant",
                        "Libelle",
                        "Binome",
                        "TypeOperation"});
            table20.AddRow(new string[] {
                        "Dépense",
                        "1",
                        "2001-01",
                        "100",
                        "Test",
                        "Marie",
                        "Commun"});
#line 123
 testRunner.And("La liste des opérations pour la période 2001-01 contient les elements suivants", ((string)(null)), table20, "And ");
#line 126
 testRunner.When("je demande à modifier le libellé de la dépense numéro 1 en \"essai\" pour la périod" +
                    "e 2001-01", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 127
 testRunner.Then("L\'opération 1 de la période 2001-01 à pour libellé \"essai\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 128
 testRunner.And("Aurélien doit la somme de 50 euros pour la période 2001-01", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Modifier le binôme d\'une opération de dépense")]
        public virtual void ModifierLeBinomeDUneOperationDeDepense()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Modifier le binôme d\'une opération de dépense", ((string[])(null)));
#line 130
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 131
testRunner.And("J\'ai demandé la création d\'une période pour le mois 1 et l\'année 2001", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "Periode",
                        "Montant",
                        "Libelle",
                        "Binome",
                        "TypeOperation"});
            table21.AddRow(new string[] {
                        "2001-01",
                        "100",
                        "Test",
                        "Marie",
                        "Commun"});
#line 132
 testRunner.And("J\'ai ajouté des dépenses dans l\'application", ((string)(null)), table21, "And ");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "OperationId",
                        "Periode",
                        "Montant",
                        "Libelle",
                        "Binome",
                        "TypeOperation"});
            table22.AddRow(new string[] {
                        "Dépense",
                        "1",
                        "2001-01",
                        "100",
                        "Test",
                        "Marie",
                        "Commun"});
#line 135
 testRunner.And("La liste des opérations pour la période 2001-01 contient les elements suivants", ((string)(null)), table22, "And ");
#line 138
 testRunner.When("je demande à modifier le binôme de la dépense numéro 1 par Aurélien pour la pério" +
                    "de 2001-01", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 139
 testRunner.Then("L\'opération 1 de la période 2001-01 à pour binôme Aurélien", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 140
 testRunner.And("Marie doit la somme de 50 euros pour la période 2001-01", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Modifier le type d\'une opération de dépense")]
        public virtual void ModifierLeTypeDUneOperationDeDepense()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Modifier le type d\'une opération de dépense", ((string[])(null)));
#line 142
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 143
testRunner.And("J\'ai demandé la création d\'une période pour le mois 1 et l\'année 2001", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "Periode",
                        "Montant",
                        "Libelle",
                        "Binome",
                        "TypeOperation"});
            table23.AddRow(new string[] {
                        "2001-01",
                        "100",
                        "Test",
                        "Marie",
                        "Commun"});
#line 144
 testRunner.And("J\'ai ajouté des dépenses dans l\'application", ((string)(null)), table23, "And ");
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "Type",
                        "OperationId",
                        "Periode",
                        "Montant",
                        "Libelle",
                        "Binome",
                        "TypeOperation"});
            table24.AddRow(new string[] {
                        "Dépense",
                        "1",
                        "2001-01",
                        "100",
                        "Test",
                        "Marie",
                        "Commun"});
#line 147
 testRunner.And("La liste des opérations pour la période 2001-01 contient les elements suivants", ((string)(null)), table24, "And ");
#line 150
 testRunner.When("je demande à modifier le type de la dépense numéro 1 en \"Avance\" pour la période " +
                    "2001-01", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 151
 testRunner.Then("L\'opération 1 de la période 2001-01 à pour type \"Avance\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 152
 testRunner.And("Aurélien doit la somme de 100 euros pour la période 2001-01", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Obtenir le solde d\'une période après de multiples opérations")]
        public virtual void ObtenirLeSoldeDUnePeriodeApresDeMultiplesOperations()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Obtenir le solde d\'une période après de multiples opérations", ((string[])(null)));
#line 154
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 155
 testRunner.And("J\'ai demandé la création d\'une période pour le mois 1 et l\'année 2001", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "Periode",
                        "Montant",
                        "Libelle",
                        "Binome",
                        "TypeOperation"});
            table25.AddRow(new string[] {
                        "2001-01",
                        "150",
                        "leclerc",
                        "Marie",
                        "Commun"});
            table25.AddRow(new string[] {
                        "2001-01",
                        "200",
                        "cadeau",
                        "Aurelien",
                        "Commun"});
            table25.AddRow(new string[] {
                        "2001-01",
                        "55",
                        "edf",
                        "Aurelien",
                        "Commun"});
            table25.AddRow(new string[] {
                        "2001-01",
                        "30",
                        "docteur",
                        "Marie",
                        "Avance"});
#line 156
 testRunner.When("J\'ajoute des dépenses dans l\'application", ((string)(null)), table25, "When ");
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "Periode",
                        "Montant",
                        "Libelle",
                        "Binome",
                        "TypeOperation"});
            table26.AddRow(new string[] {
                        "2001-01",
                        "200",
                        "CAF",
                        "Marie",
                        "Commun"});
#line 162
 testRunner.And("J\'ajoute des recettes dans l\'application", ((string)(null)), table26, "And ");
#line 165
 testRunner.Then("Marie doit la somme de 122.5 euros pour la période 2001-01", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion

