// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CoupleExpenses.Domain.Tests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CalculDeBalancePourUnePeriodeFeature : Xunit.IClassFixture<CalculDeBalancePourUnePeriodeFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "PeriodBalance.feature"
#line hidden
        
        public CalculDeBalancePourUnePeriodeFeature(CalculDeBalancePourUnePeriodeFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Calcul de balance pour une période", "\tEn tant qu\'utilisateur\r\n    Je veux que la période me calcul la balance en fonct" +
                    "ion de mes opérations\r\n    Afin de connaitre quelle somme est dûe lors d\'une pér" +
                    "iode", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="Calcul de la somme dûe en fonction des dépenses")]
        [Xunit.TraitAttribute("FeatureTitle", "Calcul de balance pour une période")]
        [Xunit.TraitAttribute("Description", "Calcul de la somme dûe en fonction des dépenses")]
        public virtual void CalculDeLaSommeDueEnFonctionDesDepenses()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Calcul de la somme dûe en fonction des dépenses", null, ((string[])(null)));
#line 6
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 7
 testRunner.Given("Une période est créée", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Montant",
                        "Libelle",
                        "Binome",
                        "Type"});
            table1.AddRow(new string[] {
                        "100",
                        "Courses",
                        "Aurelien",
                        "Commun"});
            table1.AddRow(new string[] {
                        "200",
                        "Pret",
                        "Aurelien",
                        "Avance"});
            table1.AddRow(new string[] {
                        "50",
                        "Cadeaux",
                        "Marie",
                        "Avance"});
            table1.AddRow(new string[] {
                        "300",
                        "Leclerc",
                        "Marie",
                        "Commun"});
            table1.AddRow(new string[] {
                        "700",
                        "Nounou",
                        "Marie",
                        "Commun"});
#line 8
 testRunner.When("J\'ajoute à la période les dépenses suivantes", ((string)(null)), table1, "When ");
#line 15
 testRunner.Then("le binome Aurelien doit la somme de 300 euros", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Calcul de la somme dûe en fonction des recettes")]
        [Xunit.TraitAttribute("FeatureTitle", "Calcul de balance pour une période")]
        [Xunit.TraitAttribute("Description", "Calcul de la somme dûe en fonction des recettes")]
        public virtual void CalculDeLaSommeDueEnFonctionDesRecettes()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Calcul de la somme dûe en fonction des recettes", null, ((string[])(null)));
#line 17
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 18
 testRunner.Given("Une période est créée", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Montant",
                        "Libelle",
                        "Binome",
                        "Type"});
            table2.AddRow(new string[] {
                        "100",
                        "Courses",
                        "Aurelien",
                        "Partielle"});
            table2.AddRow(new string[] {
                        "200",
                        "Pret",
                        "Aurelien",
                        "Totale"});
            table2.AddRow(new string[] {
                        "50",
                        "Cadeaux",
                        "Marie",
                        "Totale"});
            table2.AddRow(new string[] {
                        "300",
                        "Leclerc",
                        "Marie",
                        "Partielle"});
            table2.AddRow(new string[] {
                        "700",
                        "Nounou",
                        "Marie",
                        "Partielle"});
#line 19
 testRunner.When("J\'ajoute à la période les recettes suivantes", ((string)(null)), table2, "When ");
#line 26
 testRunner.Then("le binome Marie doit la somme de 300 euros", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                CalculDeBalancePourUnePeriodeFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                CalculDeBalancePourUnePeriodeFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
